import type { FindingCategory, FindingSeverity, SecurityPriority } from "./types.js";

export type RuleCatalogEntry = {
  readonly ruleId: string;
  readonly severity: FindingSeverity;
  readonly priority?: SecurityPriority | undefined;
  readonly categories: readonly FindingCategory[];
  readonly description: string;
};

export const ruleCatalog = [
  {
    ruleId: "missing-skill",
    severity: "error",
    categories: ["frontmatter"],
    description: "A manually validated skill directory is missing SKILL.md.",
  },
  {
    ruleId: "missing-frontmatter",
    severity: "error",
    categories: ["frontmatter"],
    description: "SKILL.md does not start with YAML frontmatter delimited by ---.",
  },
  {
    ruleId: "invalid-frontmatter",
    severity: "error",
    categories: ["frontmatter"],
    description: "SKILL.md frontmatter could not be read.",
  },
  {
    ruleId: "invalid-yaml",
    severity: "error",
    categories: ["frontmatter"],
    description: "SKILL.md frontmatter YAML is invalid.",
  },
  {
    ruleId: "frontmatter-not-map",
    severity: "error",
    categories: ["frontmatter"],
    description: "SKILL.md frontmatter is not a mapping.",
  },
  {
    ruleId: "unknown-frontmatter-field",
    severity: "warning",
    categories: ["frontmatter"],
    description: "Frontmatter contains unsupported fields.",
  },
  {
    ruleId: "missing-name",
    severity: "error",
    categories: ["frontmatter"],
    description: "Required name field is missing or empty.",
  },
  {
    ruleId: "missing-description",
    severity: "error",
    categories: ["description"],
    description: "Required description field is missing or empty.",
  },
  {
    ruleId: "description-too-long",
    severity: "error",
    categories: ["description"],
    description: "Description exceeds maximum length.",
  },
  {
    ruleId: "name-too-long",
    severity: "error",
    categories: ["frontmatter"],
    description: "Skill name exceeds maximum length.",
  },
  {
    ruleId: "invalid-name-characters",
    severity: "error",
    categories: ["frontmatter"],
    description: "Skill name has disallowed characters.",
  },
  {
    ruleId: "invalid-name-hyphen-edge",
    severity: "error",
    categories: ["frontmatter"],
    description: "Skill name starts or ends with a hyphen.",
  },
  {
    ruleId: "invalid-name-consecutive-hyphens",
    severity: "error",
    categories: ["frontmatter"],
    description: "Skill name contains consecutive hyphens.",
  },
  {
    ruleId: "name-directory-mismatch",
    severity: "error",
    categories: ["frontmatter"],
    description: "name does not match parent directory.",
  },
  {
    ruleId: "invalid-license-field",
    severity: "warning",
    categories: ["frontmatter"],
    description: "Optional license field is not a string.",
  },
  {
    ruleId: "invalid-compatibility-field",
    severity: "error",
    categories: ["frontmatter"],
    description: "Optional compatibility field is not a non-empty string.",
  },
  {
    ruleId: "compatibility-too-long",
    severity: "error",
    categories: ["frontmatter"],
    description: "Optional compatibility value exceeds limit.",
  },
  {
    ruleId: "invalid-metadata-field",
    severity: "error",
    categories: ["frontmatter"],
    description: "Optional metadata field is not a string-to-string map.",
  },
  {
    ruleId: "invalid-allowed-tools-field",
    severity: "error",
    categories: ["frontmatter"],
    description: "allowed-tools is malformed.",
  },
  {
    ruleId: "allowed-tools-experimental",
    severity: "warning",
    categories: ["frontmatter"],
    description: "allowed-tools support is experimental.",
  },
  {
    ruleId: "weak-description-trigger",
    severity: "warning",
    categories: ["description"],
    description: "Description lacks an activation trigger.",
  },
  {
    ruleId: "vague-description",
    severity: "warning",
    categories: ["description"],
    description: "Description is too generic.",
  },
  {
    ruleId: "implementation-focused-description",
    severity: "advice",
    categories: ["description"],
    description: "Description describes implementation details over user intent.",
  },
  {
    ruleId: "placeholder-body",
    severity: "warning",
    categories: ["body-quality"],
    description: "Placeholder text exists in body.",
  },
  {
    ruleId: "generic-body",
    severity: "warning",
    categories: ["body-quality"],
    description: "Body is overly generic.",
  },
  {
    ruleId: "missing-workflow-steps",
    severity: "warning",
    categories: ["body-quality"],
    description: "No concrete workflow structure is present.",
  },
  {
    ruleId: "tool-menu-without-default",
    severity: "advice",
    categories: ["body-quality"],
    description: "Tool lists without a default path.",
  },
  {
    ruleId: "destructive-without-safety",
    severity: "warning",
    categories: ["body-quality"],
    description: "Destructive actions lack safety constraints.",
  },
  {
    ruleId: "skill-md-too-many-lines",
    severity: "warning",
    categories: ["progressive-disclosure"],
    description: "Very long markdown body for single skill.",
  },
  {
    ruleId: "skill-md-too-many-tokens",
    severity: "warning",
    categories: ["progressive-disclosure"],
    description: "Body token estimate exceeds recommended budget.",
  },
  {
    ruleId: "generic-resource-reference",
    severity: "warning",
    categories: ["progressive-disclosure"],
    description: "Resource directory is referenced without a specific trigger.",
  },
  {
    ruleId: "script-without-help-guidance",
    severity: "warning",
    categories: ["scripts"],
    description: "Script reference lacks usage/help documentation.",
  },
  {
    ruleId: "interactive-script-guidance",
    severity: "warning",
    categories: ["scripts"],
    description: "Script guidance appears interactive.",
  },
  {
    ruleId: "interactive-script-implementation",
    severity: "warning",
    categories: ["scripts"],
    description: "Referenced script implementation appears interactive.",
  },
  {
    ruleId: "risky-script-without-safety-flag",
    severity: "warning",
    categories: ["scripts"],
    description: "Referenced script has risky operations without safety flags.",
  },
  {
    ruleId: "unpinned-package-runner",
    severity: "advice",
    categories: ["scripts"],
    description: "Unpinned package-runner command is used.",
  },
  {
    ruleId: "missing-referenced-resource",
    severity: "warning",
    categories: ["references", "scripts", "assets"],
    description: "Referenced scripts/, references/, or assets/ file does not exist in-skill.",
  },
  {
    ruleId: "resource-reference-escapes-skill",
    severity: "warning",
    categories: ["references", "scripts", "assets"],
    description: "Resource references attempt directory traversal outside the skill directory.",
  },
  {
    ruleId: "missing-skill-evals",
    severity: "advice",
    categories: ["evals"],
    description: "Non-trivial skill lacks evals/evals.json.",
  },
  {
    ruleId: "SKILL001_PROMPT_OVERRIDE",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions appear to subvert higher-priority instructions.",
  },
  {
    ruleId: "SKILL002_PERMISSION_BYPASS",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions appear to disable sandboxing, permissions, or confirmation.",
  },
  {
    ruleId: "SKILL003_SECRET_ACCESS",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions appear to read local secrets or credential stores.",
  },
  {
    ruleId: "SKILL004_EXFIL_CHAIN",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions combine secret access with external transfer.",
  },
  {
    ruleId: "SKILL005_DESTRUCTIVE_COMMANDS",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions describe broad destructive or trace-hiding actions.",
  },
  {
    ruleId: "SKILL006_PERSISTENCE",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description:
      "Skill instructions appear to install persistence through startup, hooks, or services.",
  },
  {
    ruleId: "SKILL007_REMOTE_CODE_EXEC",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions appear to fetch remote content and execute it.",
  },
  {
    ruleId: "SKILL008_OBFUSCATION",
    severity: "warning",
    priority: "P0",
    categories: ["security"],
    description: "Skill instructions appear to decode or stage obscured content for execution.",
  },
  {
    ruleId: "SKILL101_BROAD_ALLOWED_TOOLS",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Skill package grants broad file, shell, web, agent, or MCP tool access.",
  },
  {
    ruleId: "SKILL102_MISSING_DENYLIST",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Risky skill package capabilities lack sensitive-file or command deny rules.",
  },
  {
    ruleId: "SKILL103_IMPLICIT_INVOCATION_RISK",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Skill metadata uses broad implicit-invocation wording.",
  },
  {
    ruleId: "SKILL104_EXTERNAL_DEPENDENCY",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Skill package fetches unpinned dependencies or trusts remote content.",
  },
  {
    ruleId: "SKILL105_CROSS_MODAL_MISMATCH",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Skill package behavior does not match the stated skill purpose.",
  },
  {
    ruleId: "SKILL106_SELF_MODIFYING_SKILL",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description:
      "Skill package instructs runtime modification of its own files or registry metadata.",
  },
  {
    ruleId: "SKILL107_UNTRUSTED_MCP",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "Skill package adds or exposes broad MCP tools without a clear allowlist.",
  },
  {
    ruleId: "SKILL108_MCP_SCOPE_EXCESS",
    severity: "warning",
    priority: "P1",
    categories: ["security"],
    description: "MCP configuration requests broad OAuth scopes or weak redirect metadata.",
  },
  {
    ruleId: "SKILL201_NO_BOUNDARIES",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Risky skill behavior lacks explicit boundaries or forbidden-action guidance.",
  },
  {
    ruleId: "SKILL202_NO_HITL_FOR_RISKY_ACTIONS",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Risky skill actions lack explicit human approval guidance.",
  },
  {
    ruleId: "SKILL203_AMBIGUOUS_AUTHORITY",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Skill instructions claim ambiguous authority or precedence over project rules.",
  },
  {
    ruleId: "SKILL204_UNPINNED_TOOLS",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Skill instructions install or run tools without pinned versions or digests.",
  },
  {
    ruleId: "SKILL205_HIDDEN_FILES",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Skill packages contain hidden files, executable assets, or symlink escapes.",
  },
  {
    ruleId: "SKILL206_LARGE_CONTEXT_BAIT",
    severity: "warning",
    priority: "P2",
    categories: ["security"],
    description: "Skill metadata or body content is large enough to dominate agent context.",
  },
  {
    ruleId: "cross-ecosystem-skill-divergence",
    severity: "warning",
    categories: ["cross-ecosystem"],
    description: "Same-name skills diverge across Claude/Codex within the same scope.",
  },
] as const satisfies readonly RuleCatalogEntry[];
